### **Working with Large Datasets in Pandas**

#### 1. **chunksize**

What is it?

Instead of loading the entire file into memory, Pandas loads a fixed number of rows at a time (called a chunk).

This is useful when working with very large CSV files.


**Syntax:**
```python
pd.read_csv(
    "file.csv",
    chunksize=1000
)
```

**Parameter:**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Parameter</th>
<th>Meaning</th>
</tr>
<tr>
<td><i>chunksize</i></td>
<td>Number of rows to read in each chunk</td>
</tr>
</table>

In [1]:
import pandas as pd
df = pd.read_csv(
    r'sample_datasets\large_datasets\movies_dataset.csv',
    usecols=['MovieID', 'Title', 'Genre','Country', 'ReleaseYear','IMDbRating','Director', 'LeadActor']
)
print(df.shape)
print(df.info())

(400000, 8)
<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   MovieID      400000 non-null  int64
 1   Title        400000 non-null  str
 2   Genre        400000 non-null  str
 3   ReleaseYear  400000 non-null  int64
 4   Country      400000 non-null  str
 5   IMDbRating   400000 non-null  float64
 6   Director     400000 non-null  str
 7   LeadActor    400000 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 44.4 MB
None

##### **Read in chunks**

In [2]:

chunks = pd.read_csv(
    r'sample_datasets\large_datasets\movies_dataset.csv',
    usecols=['MovieID', 'Title', 'Genre','Country','IMDbRating','Director'],
    chunksize=20000
)
for chunk in chunks:
    print(chunk.head)

<bound method NDFrame.head of        MovieID                         Title        Genre Country  IMDbRating  \
0            1          Might toward capital       Comedy   China         6.2
1            2         He however experience       Comedy     USA         5.2
2            3  Star responsibility politics       Comedy     USA         5.5
3            4                  Exactly live       Comedy     USA         7.3
4            5      Focus improve especially  Documentary   India         6.1
...        ...                           ...          ...     ...         ...
19995    19996              Big travel speak        Drama     USA         4.4
19996    19997                         Later       Action     USA         7.0
19997    19998             Current boy crime       Action     USA         6.7
19998    19999                        Listen        Drama     USA         8.4
19999    20000              Left institution       Sci-Fi     USA         9.5

                Director
0         Kristina Moore
1        Benjamin Hudson
2            Kayla Young
3           Michael Ross
4         Faith Franklin
...                  ...
19995  Dr. Jonathan Long
19996        Paul Rogers
19997  Jennifer Atkinson
19998     Robert Webster
19999        Kayla Young

[20000 rows x 6 columns]>
<bound method NDFrame.head of        MovieID               Title        Genre Country  IMDbRating  \
20000    20001  Require second job     Thriller   Japan         5.2
20001    20002                Fire       Comedy  Canada         4.4
20002    20003   May radio citizen       Action   India         8.8
20003    20004          Collection       Action     USA         4.8
20004    20005         Leave apply  Documentary     USA         4.7
...        ...                 ...          ...     ...         ...
39995    39996   Together thousand       Comedy     USA         4.9
39996    39997    Big travel speak        Drama     USA         6.0
39997    39998         Detail long     Thriller     USA         6.6
39998    39999      Fall structure        Drama   China         5.3
39999    40000            Guy sure      Romance     USA         8.4

              Director
20000   Kristina Moore
20001    Nathan Bolton
20002    Diane Skinner
20003   Elizabeth Lane
20004        Chad Koch
...                ...
39995  Amanda Cantrell
39996  Nicholas Murphy
39997     Donna Wagner
39998       Jeremy Ray
39999    Manuel Benton

[20000 rows x 6 columns]>
<bound method NDFrame.head of        MovieID                       Title   Genre Country  IMDbRating  \
40000    40001              Smile too into  Horror      UK         8.9
40001    40002                   Be reduce   Drama     USA         5.7
40002    40003         Industry house note   Drama     USA         4.8
40003    40004    Huge assume vote account  Comedy     USA        10.0
40004    40005          Art paper position  Horror     USA         9.2
...        ...                         ...     ...     ...         ...
59995    59996       Cold thousand himself  Horror     USA         7.3
59996    59997                       Where   Drama  Canada         7.5
59997    59998       Parent determine part   Drama     USA         3.3
59998    59999  Attention mention audience   Drama     USA         7.3
59999    60000     Rock manager morning no  Action     USA         7.0

                Director
40000  Jessica Rodriguez
40001     Francisco Ford
40002    Nicholas Murphy
40003  Courtney Reynolds
40004   Suzanne Gonzalez
...                  ...
59995         Adam Brown
59996    Benjamin Hudson
59997      Michael Chung
59998    Anthony Rowland
59999       Jeremy Davis

[20000 rows x 6 columns]>
<bound method NDFrame.head of        MovieID                         Title     Genre    Country  IMDbRating  \
60000    60001                  Million next  Thriller        USA         6.2
60001    60002                    Minute eye  Thriller      Japan         4.7
60002    60003     Minute rise quite medical  Thriller  Australia         6.0
60003    60004          Exactly son discover   Romance        USA         6.7
60004    60005          Could avoid hospital    Sci-Fi        USA         5.0
...        ...                           ...       ...        ...         ...
79995    79996  Process personal suffer move    Action        USA         7.2
79996    79997    Performance accept network   Romance         UK         8.9
79997    79998                      Specific    Action        USA         7.3
79998    79999                    Mr student    Action        USA         4.2
79999    80000                  Building man  Thriller        USA         5.5

                Director
60000     Heidi Cisneros
60001        Lisa Atkins
60002          Ryan Tate
60003       James Miller
60004        David Perez
...                  ...
79995     Caitlin Brewer
79996   Suzanne Gonzalez
79997  Amanda Montgomery
79998       Rachel Kirby
79999      David Charles

[20000 rows x 6 columns]>
<bound method NDFrame.head of        MovieID                   Title    Genre Country  IMDbRating  \
80000    80001               View open  Romance     USA         2.6
80001    80002      Trip number forget   Comedy     USA         5.3
80002    80003          Each beautiful    Drama     USA         7.7
80003    80004            Pressure and   Horror     USA         4.7
80004    80005                   Tough  Romance     USA         7.4
...        ...                     ...      ...     ...         ...
99995    99996   Improve community boy    Drama     USA         4.7
99996    99997        Meeting strategy    Drama     USA         6.1
99997    99998    State social full if   Comedy     USA         7.8
99998    99999           Behind arrive   Horror  Canada         6.9
99999   100000  Although every reality  Romance  Canada         8.7

                  Director
80000      Anthony Rowland
80001        Manuel Benton
80002    Amanda Montgomery
80003  Christian Hernandez
80004      Nicholas Murphy
...                    ...
99995            Chad Koch
99996           Donna Hall
99997         Tracy Tucker
99998         Tracy Tucker
99999         James Wright

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                        Title        Genre Country  IMDbRating  \
100000   100001     Finally including forget       Comedy     USA         4.6
100001   100002  Current study describe star       Comedy     USA         8.2
100002   100003                Set challenge       Horror     USA         5.9
100003   100004                 More the gas  Documentary     USA         8.0
100004   100005      Behind spring including        Drama     USA         7.5
...         ...                          ...          ...     ...         ...
119995   119996            Subject dark road        Drama     USA         5.0
119996   119997               Quality father       Action     USA         6.7
119997   119998           Anyone wonder know        Drama   China         4.4
119998   119999           West adult message       Action     USA         7.0
119999   120000     Explain later happy born       Horror     USA         5.4

                Director
100000     Lori Callahan
100001        John Jones
100002    Barbara Torres
100003  Jeffrey Myers MD
100004       Jerry Owens
...                  ...
119995     Joseph Willis
119996    Francisco Ford
119997     Diane Skinner
119998       Kayla Young
119999    Brooke Morales

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                           Title    Genre    Country  \
120000   120001              Church create drug  Romance  Australia
120001   120002          Without memory ability   Action        USA
120002   120003               Section eight how   Comedy        USA
120003   120004              National bed about   Comedy        USA
120004   120005            School actually wide   Comedy      India
...         ...                             ...      ...        ...
139995   139996  Dream attention central person   Action      India
139996   139997          Senior general mention   Horror        USA
139997   139998                       Else goal   Comedy        USA
139998   139999                          Garden   Action        USA
139999   140000                  Crime recently   Horror        USA

        IMDbRating                  Director
120000         6.4                John Jones
120001         7.7         Courtney Reynolds
120002         5.5              Michael Ross
120003         5.4  Mrs. Hannah Campbell DDS
120004         8.3               Karen Smith
...            ...                       ...
139995         9.0            Brandon Fuller
139996         3.9         Amanda Montgomery
139997         3.7              Michael Ross
139998         6.0                Mark Moody
139999         6.2              Eric Ramirez

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                    Title        Genre    Country  IMDbRating  \
140000   140001              Energy play       Action        USA         6.6
140001   140002        East garden until      Romance        USA         8.0
140002   140003     Return clear country       Comedy        USA         6.4
140003   140004            Him pass task       Action        USA         7.1
140004   140005       Listen walk author       Comedy  Australia         7.8
...         ...                      ...          ...        ...         ...
159995   159996                Argue and  Documentary        USA         7.9
159996   159997         Technology often       Action        USA         5.9
159997   159998              Child plant       Comedy        USA        10.0
159998   159999                Fish test      Romance        USA         3.7
159999   160000  Bank education training       Sci-Fi     Canada         5.0

             Director
140000    Jason Jones
140001  Sharon Wilson
140002   Rachel Kirby
140003  Charles Lopez
140004   Tracy Tucker
...               ...
159995   Daniel Brown
159996  Jessica Singh
159997  Julie Maxwell
159998    Lisa Atkins
159999   Brenda Smith

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                          Title     Genre    Country  \
160000   160001               Season structure    Comedy        USA
160001   160002               Happen difficult    Action        USA
160002   160003            Air meeting college   Romance  Australia
160003   160004  Tell road professional within    Action        USA
160004   160005               Bag black theory     Drama        USA
...         ...                            ...       ...        ...
179995   179996           Final need card they    Horror        USA
179996   179997                     Fine focus    Comedy  Australia
179997   179998                       Fish bar  Thriller      China
179998   179999                            Gun    Comedy         UK
179999   180000                   There theory    Horror        USA

        IMDbRating        Director
160000         7.8    Gary Simmons
160001         6.3    Gary Simmons
160002         6.3     Kayla Young
160003         7.0  Brooke Morales
160004         6.0   Janice Taylor
...            ...             ...
179995         6.7      Jeremy Ray
179996         6.6    Sara Higgins
179997         7.7    James Miller
179998         5.5   Anthony Henry
179999         9.1      Maria Lane

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                       Title        Genre Country  IMDbRating  \
180000   180001                        Born  Documentary     USA         7.1
180001   180002  Several education over his       Action     USA         8.2
180002   180003            Form music smile        Drama     USA         8.4
180003   180004                      Listen        Drama     USA         7.8
180004   180005       Specific class street        Drama     USA         8.3
...         ...                         ...          ...     ...         ...
199995   199996         Campaign take small      Romance  Canada         7.5
199996   199997               System sign a       Action     USA         2.5
199997   199998           Reach another out        Drama     USA         6.2
199998   199999         Society store glass      Romance     USA         7.4
199999   200000             Beyond end seem       Action     USA         7.0

                 Director
180000        David Perez
180001       Troy Cochran
180002        Diana Davis
180003     Crystal Harris
180004      Lori Callahan
...                   ...
199995        James Cross
199996      Charles Lopez
199997       Daniel Brown
199998   Robert Hendricks
199999  Jessica Rodriguez

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                      Title        Genre Country  IMDbRating  \
200000   200001               Lawyer piece  Documentary     USA         6.1
200001   200002       Time animal national      Romance     USA         6.0
200002   200003  Picture would bad student        Drama     USA         8.4
200003   200004       Respond fish western     Thriller     USA         7.2
200004   200005  Serve mention live rather       Comedy     USA         4.9
...         ...                        ...          ...     ...         ...
219995   219996           Other sport thus      Romance     USA         7.4
219996   219997                Your a book        Drama     USA         6.0
219997   219998    Suddenly authority part       Action     USA         6.0
219998   219999                Whom entire       Comedy     USA         7.2
219999   220000              Space meeting       Action     USA         5.4

                 Director
200000     Chad Peters MD
200001       Brenda Smith
200002  Jessica Rodriguez
200003       Daniel Brown
200004     Jennifer Henry
...                   ...
219995      Nathan Bolton
219996     Jennifer Henry
219997     Chad Peters MD
219998      William Banks
219999  Courtney Reynolds

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                       Title     Genre Country  IMDbRating  \
220000   220001        Quality country hard   Romance     USA         6.5
220001   220002  Increase tonight hand full    Comedy     USA         8.9
220002   220003    Bad throughout eye catch    Comedy     USA         9.3
220003   220004                Whose speech    Horror     USA         6.7
220004   220005                   Wait once    Comedy     USA         7.8
...         ...                         ...       ...     ...         ...
239995   239996                  Whose food    Comedy     USA         6.5
239996   239997               Expert writer  Thriller     USA         6.8
239997   239998    Statement phone standard    Action     USA         7.5
239998   239999                         Per     Drama     USA         8.5
239999   240000                 Scene treat  Thriller     USA         6.9

                 Director
220000     Brandon Fuller
220001        James Cross
220002     Brian Robinson
220003    Benjamin Hudson
220004   Adriana Campbell
...                   ...
239995  Samantha Campbell
239996       Susan Farley
239997      David Charles
239998  Jacqueline Briggs
239999      Melanie Olson

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                 Title     Genre Country  IMDbRating  \
240000   240001  Wrong value cultural   Romance     USA         7.6
240001   240002      Seem stage child   Romance     USA         6.0
240002   240003                 Large  Thriller   Japan         6.2
240003   240004         Model try Mrs    Action     USA         3.1
240004   240005            Rate force  Thriller     USA         8.1
...         ...                   ...       ...     ...         ...
259995   259996    Letter interesting     Drama  France         4.8
259996   259997     Challenge college   Romance   India         3.8
259997   259998            Meet black    Comedy     USA         5.3
259998   259999  Wish no likely young    Comedy   China         6.6
259999   260000              Actually    Sci-Fi     USA         6.9

              Director
240000  Elizabeth Lane
240001    Michael Ross
240002   Michael Chung
240003    Emily Miller
240004  Jennifer Henry
...                ...
259995  Elizabeth Lane
259996   David Charles
259997  Patricia Munoz
259998     Kevin Green
259999   Tyler Sanchez

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                 Title        Genre      Country  IMDbRating  \
260000   260001         Nice recently  Documentary          USA         6.9
260001   260002   Safe difficult last       Horror          USA         8.3
260002   260003       Factor in plant       Comedy          USA         8.8
260003   260004  Realize particularly       Comedy          USA         7.2
260004   260005         Five describe       Comedy          USA         5.9
...         ...                   ...          ...          ...         ...
279995   279996      Media senior gun       Comedy          USA         5.7
279996   279997           Return line       Comedy  South Korea         7.1
279997   279998      Different middle        Drama          USA         6.7
279998   279999     Spring likely key       Horror          USA         9.9
279999   280000          Think member        Drama          USA         4.8

                Director
260000       James Cross
260001    Darlene Murphy
260002   Jennifer Miller
260003     Sharon Wilson
260004      Joshua Baker
...                  ...
279995      Joshua Baker
279996      Donna Wagner
279997     Lori Callahan
279998  Adriana Campbell
279999      Susan Farley

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                  Title        Genre  Country  IMDbRating  \
280000   280001                   Cold     Thriller       UK         8.5
280001   280002          Artist region       Action   Canada         5.1
280002   280003            Force under      Romance      USA         8.8
280003   280004           Remember cup       Comedy       UK         6.0
280004   280005    Tough least medical     Thriller      USA         6.5
...         ...                    ...          ...      ...         ...
299995   299996                  Sport        Drama  Germany         5.7
299996   299997  Someone anyone moment  Documentary      USA         4.5
299997   299998         Method prepare     Thriller      USA         5.4
299998   299999                Rule no       Action      USA         7.8
299999   300000            Hand spring  Documentary      USA         4.2

                  Director
280000         Jason Jones
280001      Darlene Murphy
280002         Jason Jones
280003     Darrell Carlson
280004        Sophia Gomez
...                    ...
299995        Benjamin Ray
299996       Diane Skinner
299997  Charlotte Williams
299998       Jessica Singh
299999  Mr. Drew Clark Jr.

[20000 rows x 6 columns]>
<bound method NDFrame.head of         MovieID                      Title        Genre Country  IMDbRating  \
300000   300001                        Hot  Documentary     USA         6.7
300001   300002              Quite medical        Drama     USA         4.8
300002   300003  Religious brother economy     Thriller   China         5.0
300003   300004                Event later        Drama   India         7.4
300004   300005  Would before particularly        Drama     USA         7.7
...         ...                        ...          ...     ...         ...
319995   319996                          A        Drama     USA         6.6
319996   319997             Gas commercial        Drama     USA         6.1
319997   319998                   Card arm        Drama     USA         2.7
319998   319999              Magazine goal       Comedy     USA         7.7
319999   320000                 Week maybe        Drama   Japan         7.5

                 Director
300000     Francisco Ford
300001       Troy Cochran

##### **Important**

Iterator can only be used once.

**This works**

```python
chunks = pd.read_csv("employees.csv", chunksize=1000)

for chunk in chunks:
    print(chunk.head())
```

T**his does not work**

```python
chunks = pd.read_csv("employees.csv", chunksize=1000)

for chunk in chunks:
    print(chunk.head())

for data in chunks:
    print(data.head())   # No output
```

Why?

Because chunks is an iterator. Once it reaches the end of the file, it is exhausted.

Read the file again if you need another loop.

#### 2. **iterator**
*iterator=True* creates an iterator object instead of loading all data immediately.

You can manually read chunks using get_chunk().

**Syntax:**
```python
pd.read_csv(
    "file.csv",
    iterator=True
)
```

In [3]:
reader = pd.read_csv(
    r'sample_datasets\large_datasets\movies_dataset.csv',
    usecols=['MovieID', 'Title', 'Genre','Country','IMDbRating','Director'],
    iterator=True
)

Read First 10 Rows

In [4]:
reader.get_chunk(10)

,MovieID,Title,Genre,Country,IMDbRating,Director
0,1,Might toward capital,Comedy,China,6.2,Kristina Moore
1,2,He however experience,Comedy,USA,5.2,Benjamin Hudson
2,3,Star responsibility politics,Comedy,USA,5.5,Kayla Young
3,4,Exactly live,Comedy,USA,7.3,Michael Ross
4,5,Focus improve especially,Documentary,India,6.1,Faith Franklin
5,6,Deal reveal fine,Drama,USA,8.9,Thomas Peterson
6,7,Drug when,Comedy,USA,3.6,Maria Lane
7,8,Almost option of,Horror,USA,7.3,Diane Skinner
8,9,Film about training,Drama,USA,6.9,Albert Phillips
9,10,Begin difficult world,Documentary,USA,8.4,Francisco Ford

Read Next 20 Rows

In [5]:
reader.get_chunk(20)

,MovieID,Title,Genre,Country,IMDbRating,Director
10,11,Eight,Documentary,USA,6.7,Mark Brooks
11,12,Score by attorney,Comedy,India,8.7,Robert Webster
12,13,Nice piece near,Drama,USA,4.4,Michelle Collins
13,14,Among money,Drama,USA,4.6,Philip Simmons
14,15,Purpose miss others show,Action,USA,6.5,Patricia Munoz
15,16,Similar off,Drama,USA,5.0,Jason Jones
16,17,Accept past she somebody,Horror,USA,4.2,Mr. Jorge Anderson
17,18,Memory blue,Thriller,USA,8.1,Mr. Jorge Anderson
18,19,Sport just score,Drama,India,4.2,Amanda Cantrell
19,20,Mrs close hotel,Comedy,USA,7.4,Kimberly Barker
20,21,Agree garden,Romance,USA,7.0,Rachel Hayes
21,22,Short phone sometimes product,Drama,USA,5.5,Sophia Gomez
22,23,Identify,Drama,USA,5.3,Robert Webster
23,24,Large over the,Comedy,India,6.7,Colleen Willis
24,25,Picture value,Drama,USA,6.6,Mark Brooks
25,26,Seem into beyond,Comedy,USA,5.2,Faith Franklin
26,27,Bad side,Drama,USA,6.9,Abigail Robles
27,28,Second,Romance,USA,5.6,Robert Webster
28,29,Character institution good thousand,Sci-Fi,USA,9.3,Chad Koch
29,30,Professor either,Drama,USA,8.6,Jacqueline Briggs

Think of a water tap.

**chunksize**

Someone pours one bucket every minute.

**iterator**

You open the tap whenever you want.

**Difference**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>chunksize</th>
<th>iterator</th>
</tr>
<tr>
<td>Automatic</td>
<td>Manual</td>
</tr>
<tr>
<td>Easy for loops</td>
<td>You call get_chunk() yourself</td>
</tr>
<tr>
<td>Used most often</td>
<td>Used when you need more control</td>
</tr>
</table>

#### 3. **Memory Optimization**

Large datasets consume lots of RAM.

You can reduce memory usage by choosing better data types.

In [6]:
df = pd.DataFrame({
    "Age":[25,30,40],
    "Salary":[50000,60000,70000]
})

In [7]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     3 non-null      int64
 1   Salary  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

**Converting DataTypes:**

- Convert Age DataType From int64 to int8
- Convert Salary DataType From int64 to float32

In [8]:
df['Age'] = df['Age'].astype('int8')
df['Salary'] = df['Salary'].astype('float32')

**Checking memory_usage Again**

In [9]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     3 non-null      int8
 1   Salary  3 non-null      float32
dtypes: float32(1), int8(1)
memory usage: 147.0 bytes

#### 4. **Categorical Data**

What is categorical data?

Columns that contain a small number of repeated values.

Examples:

- Gender
- Department
- City
- Product Category
- Status

Instead of storing the full text repeatedly, Pandas stores each unique value once and uses integer codes internally.

In [10]:
df = pd.read_csv(
    r'sample_datasets\large_datasets\movies_dataset.csv',
    usecols=['MovieID', 'Title', 'Genre','Country','IMDbRating','Director']
)

**Convert to category**

In [11]:
df['Genre'] = df['Genre'].astype('category')

**Check datatype**

In [12]:
df.dtypes

MovieID          int64
Title              str
Genre         category
Country            str
IMDbRating     float64
Director           str
dtype: object

**Categories**

In [13]:
df['Genre'].cat.categories

Index(['Action', 'Comedy', 'Documentary', 'Drama', 'Horror', 'Romance',
       'Sci-Fi', 'Thriller'],
      dtype='str')

**Category codes**

In [14]:
df['Genre'].cat.codes

0         1
1         1
2         1
3         1
4         2
         ..
399995    3
399996    1
399997    1
399998    0
399999    7
Length: 400000, dtype: int8

#### **Summary**

<table style="margin-left: 0; margin-right: auto;">
<tr>
<th>Topic</th>
<th>Purpose</th>
<th>Best Use</th>
</tr>
<tr>
<td><i>chunksize</i></td>
<td>Read file in parts</td>
<td>Large CSV files</td>
</tr>
<tr>
<td><i>iterator=True</i></td>
<td>Manual chunk reading</td>
<td>Controlled processing</td>
</tr>
<tr>
<td>Memory optimization</td>
<td>Reduce RAM usage</td>
<td>Large datasets</td>
</tr>
<tr>
<td>Categorical data</td>
<td>Compress repeated text values</td>
<td>Columns with few unique values</td>
</tr>
</table>